In [1]:
from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
soup=BeautifulSoup(page.content)
Team=[]   
for i in soup.find_all('span',class_="u-hide-phablet"):
    Team.append(i.text)
    
Matches=[]   
for i in soup.find_all('td',class_="table-body__cell u-center-text"):
    Matches.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="rankings-block__banner--rating u-text-right"):
    Rating.append(i.text)

In [4]:
from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
soup=BeautifulSoup(page.content)
name=[]   
for i in soup.find_all('td',class_="table-body__cell rankings-table__name name"):
    name.append(i.text)
    
country=[]   
for i in soup.find_all('span',class_="table-body__logo-text"):
    country.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="table-body__cell rating"):
    Rating.append(i.text)
    
    
import pandas as pd
df= pd.DataFrame({'NAME':name,'COUNTRY':country,'RATING':Rating})
df

                    NAME COUNTRY RATING
0        \nMithali Raj\n     IND    735
1     \nTammy Beaumont\n     ENG    707
2        \nMeg Lanning\n     AUS    706
3        \nBeth Mooney\n     AUS    705
4        \nLizelle Lee\n      SA    702
..                   ...     ...    ...
94     \nTaniya Bhatia\n     IND    199
95    \nLeigh Kasperek\n      NZ    199
96       \nHannah Rowe\n      NZ    198
97        \nAnne Bosch\n      SA    195
98  \nOrla Prendergast\n     IRE    193

[99 rows x 3 columns]

In [5]:
from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
soup=BeautifulSoup(page.content)
name=[]   
for i in soup.find_all('td',class_="table-body__cell rankings-table__name name"):
    name.append(i.text)
    
country=[]   
for i in soup.find_all('span',class_="table-body__logo-text"):
    country.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="table-body__cell rating"):
    Rating.append(i.text)
    
    
import pandas as pd
df= pd.DataFrame({'NAME':name,'COUNTRY':country,'RATING':Rating})
df

                     NAME COUNTRY RATING
0      \nNatalie Sciver\n     ENG    351
1      \nMarizanne Kapp\n      SA    327
2         \nAmelia Kerr\n      NZ    312
3       \nDeepti Sharma\n     IND    309
4     \nKatherine Brunt\n     ENG    273
5       \nJess Jonassen\n     AUS    263
6     \nStafanie Taylor\n      WI    262
7    \nAshleigh Gardner\n     AUS    256
8     \nHayley Matthews\n      WI    254
9       \nSophie Devine\n      NZ    251
10   \nDane van Niekerk\n      SA    233
11     \nJhulan Goswami\n     IND    227
12       \nRumana Ahmed\n     BAN    195
13           \nNida Dar\n     PAK    186
14          \nSune Luus\n      SA    170
15     \nHeather Knight\n     ENG    156
16  \nSophie Ecclestone\n     ENG    152
17         \nKate Cross\n     ENG    142
18      \nShikha Pandey\n     IND    141