In [3]:

from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/test')
soup=BeautifulSoup(page.content)
Team=[]   
for i in soup.find_all('span',class_="u-hide-phablet"):
    Team.append(i.text)
    
Matches=[]   
for i in soup.find_all('td',class_="table-body__cell u-center-text"):
    Matches.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="table-body__cell u-text-right rating"):
    Rating.append(i.text)

In [18]:
from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
soup=BeautifulSoup(page.content)
name=[]   
for i in soup.find_all('td',class_="table-body__cell rankings-table__name name"):
    name.append(i.text)
    
country=[]   
for i in soup.find_all('span',class_="table-body__logo-text"):
    country.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="table-body__cell rating"):
    Rating.append(i.text)
    
    
import pandas as pd
df= pd.DataFrame({'NAME':name,'COUNTRY':country,'RATING':Rating})
df

                   NAME COUNTRY RATING
0       \nVirat Kohli\n     IND    811
1      \nRohit Sharma\n     IND    791
2   \nQuinton de Kock\n      SA    783
3       \nAaron Finch\n     AUS    779
4    \nJonny Bairstow\n     ENG    775
..                  ...     ...    ...
94   \nKieron Pollard\n      WI    400
95   \nCraig Williams\n     NAM    399
96     \nSam Billings\n     ENG    396
97     \nMonank Patel\n     USA    394
98   \nJatinder Singh\n     OMA    394

[99 rows x 3 columns]

In [19]:
from bs4 import BeautifulSoup
import requests
page= requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
soup=BeautifulSoup(page.content)
name=[]   
for i in soup.find_all('td',class_="table-body__cell rankings-table__name name"):
    name.append(i.text)
    
country=[]   
for i in soup.find_all('span',class_="table-body__logo-text"):
    country.append(i.text)
    
    
Rating=[]   
for i in soup.find_all('td',class_="table-body__cell rating"):
    Rating.append(i.text)
    
    
import pandas as pd
df= pd.DataFrame({'NAME':name,'COUNTRY':country,'RATING':Rating})
df

                      NAME COUNTRY RATING
0       \nJosh Hazlewood\n     AUS    709
1         \nChris Woakes\n     ENG    700
2           \nMatt Henry\n      NZ    691
3     \nMujeeb Ur Rahman\n     AFG    681
4       \nJasprit Bumrah\n     IND    679
..                     ...     ...    ...
94          \nMark Adair\n     IRE    357
95     \nDonald Tiripano\n     ZIM    356
96  \nSharafuddin Ashraf\n     AFG    356
97     \nGeorge Dockrell\n     IRE    353
98       \nKyle Jamieson\n      NZ    352

[99 rows x 3 columns]

In [17]:

https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting