In [1]:
#lets import all required librabries
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
#lets first connect to web driver
driver=webdriver.Chrome(r'C:/Users/jishn/Downloads/chromedriver_win32/chromedriver.exe')   
driver=webdriver.Chrome('chromedriver.exe')
url='http://www.myntra.com/shoes'
driver.get(url)

In [4]:
Price_check=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label/div')
Price_check.click()

In [5]:
Color_check=driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label/div')
Color_check.click()

In [6]:
#lets extract all web elements having job titles
title_tags=driver.find_elements_by_xpath('//h3[@class="product-brand"]')
titles=[]

for i in title_tags:
    titles.append(i.text)
    
price_tags=driver.find_elements_by_xpath('//div[@class="product-price"]')
price_names=[]

for i in price_tags:
    price_names.append(i.text)
    
des_tags=driver.find_elements_by_xpath('//h4[@class="product-product"]')
des=[]

for i in des_tags:
    des.append(i.text)

In [8]:
len(titles),len(price_names),len(des)

(50, 50, 50)

In [9]:
Flipkart=pd.DataFrame()
Flipkart['Products']=titles
Flipkart['Description']=des
Flipkart['Price']=price_names
Flipkart

,Products,Description,Price
0,ALDO,Men Leather Driving Shoes,Rs. 12999
1,Reebok,Men Zig Dynamica 2.0 Running,Rs. 7999
2,Nike,Men Winflo 7 Running Shoes,Rs. 7995
3,ALDO,Men Printed Sneakers,Rs. 9099Rs. 12999(30% OFF)
4,Tommy Hilfiger,Men Cleated Leather Sneakers,Rs. 7739Rs. 8599(10% OFF)
5,ALDO,Men Woven Design Sneakers,Rs. 13999
6,Puma,Men Jamming 2.0 Running Shoes,Rs. 12999
7,Puma,Eternity Nitro Running Shoes,Rs. 12999
8,Puma,Electrify Nitro Running Shoes,Rs. 9999
9,Hush Puppies,Men Solid Leather Formal Slip-Ons,Rs. 7649Rs. 8999(15% OFF)
10,Nike,Men Air Max Dawn Sneakers,Rs. 10995
11,Puma,Men FUSE Training Shoes,Rs. 7999
12,Puma,Men Training or Gym Shoes,Rs. 7999
13,ASICS,Women Running Shoes,Rs. 7999
14,Skechers,Men Go Run Hyper Burst Running,Rs. 7224Rs. 8499(15% OFF)
15,Hush Puppies,Men Solid Leather Formal Slip-Ons,Rs. 8499Rs. 9999(15% OFF)
16,Hush Puppies,Men Formal Derbys,Rs. 8499Rs. 9999(15% OFF)
17,Saint G,Men Mid-Top Chelsea Boots,Rs. 10500Rs. 10900(Rs. 400 OFF)
18,Bugatti,Men Solid Leather Formal Derbys,Rs. 9499
19,Puma,Women Velocity NITRO Runners,Rs. 8249Rs. 10999(25% OFF)
20,Hush Puppies,Men Solid Formal Slip-Ons,Rs. 8499Rs. 9999(15% OFF)
21,J.FONTINI,Men Black Leather Loafers,Rs. 8490
22,Saint G,Women Leather Block Heels,Rs. 9500
23,TRIBAN By Decathlon,Unisex Training or Gym Shoes,Rs. 8579Rs. 10999(22% OFF)
24,Hush Puppies,Men Solid Leather Formal Derbys,Rs. 8499Rs. 9999(15% OFF)
25,Columbia,Men FACET OUTDRY Trekking Shoe,Rs. 12999
26,Sole To Soul,Women Block Heeled Boots,Rs. 8900
27,Tommy Hilfiger,Women CLEAT Textured Sneakers,Rs. 7739Rs. 8599(10% OFF)
28,Tommy Hilfiger,Leather Sandals,Rs. 7599
29,MANGO,Women Solid Sneakers,Rs. 8990
30,Puma,Women Eternity NITRO Shoes,Rs. 9099Rs. 12999(30% OFF)
31,Heel & Buckle London,Men Suede Loafers,Rs. 12990
32,Geox,Men Striped Leather Sneakers,Rs. 9990
33,Geox,Men Leather Driving Shoes,Rs. 9499
34,ALDO,Wedge Sandals,Rs. 7999
35,ALDO,Leather Slim Heels,Rs. 8399Rs. 11999(30% OFF)
36,ALDO,Wedge Sandals,Rs. 7999
37,J.FONTINI,Men Textured Leather Loafers,Rs. 8490
38,Bugatti,Men Textured Leather High-Top Flat Boots,Rs. 8399Rs. 11999(30% OFF)
39,J.FONTINI,Men Textured Leather Loafers,Rs. 7990
40,Saint G,Leather High-Top Heeled Boots,Rs. 10625Rs. 12500(15% OFF)
41,DAVINCHI,Men Textured Formal Leather Loafers,Rs. 8990
42,MANGO,Women Heeled Leather Loafers,Rs. 7990
43,Sole To Soul,High-Top Block Heeled Boots,Rs. 7900
44,Geox,Women Leather Pumps,Rs. 8999
45,Sole To Soul,High-Top Platform Heeled Boots,Rs. 8900
46,Sole To Soul,Suede High-Top Block Heeled Boots,Rs. 9500
47,ROSSO BRUNELLO,Printed PU Kitten Sandals,Rs. 8499
48,Heel & Buckle London,Men Formal Leather Derby,Rs. 7990
49,DAVINCHI,Solid Slip On Shoes,Rs. 7990