In [1]:
#lets import all required librabries
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
#lets first connect to web driver
driver=webdriver.Chrome(r'C:/Users/jishn/Downloads/chromedriver_win32/chromedriver.exe')   
driver=webdriver.Chrome('chromedriver.exe')
url='http://www.flipkart.com/'
driver.get(url)

In [5]:
search_product=driver.find_element_by_class_name("_3704LK")
search_product.send_keys("Sneakers")

In [8]:
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
search_btn.click()

In [10]:
#lets extract all web elements having job titles
title_tags=driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
titles=[]

for i in title_tags:
    titles.append(i.text)

In [11]:
titles

['HIGHLANDER',
 'HIGHLANDER',
 'DUNKASTON',
 'BRUTON',
 'World Wear Footwear',
 'Chevit',
 'KWIK FIT',
 'RapidBox',
 'BRUTON',
 'World Wear Footwear',
 'corsac',
 'BIRDE',
 'BRUTON',
 'D-SNEAKERZ',
 'Magnolia',
 'HIGHLANDER',
 'BRUTON',
 'Shoes Bank',
 'URBANBOX',
 'HIGHLANDER',
 'Labbin',
 'Magnolia',
 'Kraasa',
 'HIGHLANDER',
 'TR',
 'RapidBox',
 'Rzisbo',
 'Echor',
 'Stefano Rads',
 'ASTEROID',
 'CLYMB',
 'RapidBox',
 'Airland',
 'SCATCHITE',
 'luxury fashion',
 'BIRDE',
 'Zsyto',
 'aadi',
 'Chevit',
 'HIGHLANDER']

In [12]:
    
price_tags=driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
price_names=[]

for i in price_tags:
    price_names.append(i.text)

In [13]:
price_names

['₹995',
 '₹719',
 '₹343',
 '₹259',
 '₹199',
 '₹649',
 '₹399',
 '₹640',
 '₹299',
 '₹199',
 '₹449',
 '₹399',
 '₹471',
 '₹299',
 '₹448',
 '₹719',
 '₹299',
 '₹298',
 '₹198',
 '₹719',
 '₹499',
 '₹448',
 '₹444',
 '₹796',
 '₹360',
 '₹680',
 '₹494',
 '₹499',
 '₹240',
 '₹474',
 '₹616',
 '₹630',
 '₹198',
 '₹398',
 '₹489',
 '₹399',
 '₹311',
 '₹339',
 '₹259',
 '₹995']

In [14]:
des_tags=driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
des=[]

for i in des_tags:
    des.append(i.text)

In [15]:
des

['Sneakers For Men',
 'Sneakers For Men',
 'Modern Trendy Sneakers Shoes Sneakers For Men',
 'Sneakers For Men',
 'Super Stylish & Trendy Combo Pack of 02 Pairs Sneakers ...',
 'Kwik FIT casual sneaker shoes and partywear shoes Casua...',
 'Sneaker Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'STYLISH MENS BLACK AND WHITE SNEAKER Sneakers For Men',
 'Stylish Comfortable Lightweight, Breathable Walking Sho...',
 'Modern & Trendy Collection Combo Pack of 02 Shoes for M...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Sneakers For Men',
 'Sneakers For Men',
 'Lattest Sneakers Shoe Sneakers For Men',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Series 7 Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 "Echor Men's Sneakers Fashion Lightweight Running Shoes ...",
 "Original Luxury Branded Fashionable Men's Casual Walkin...",
 'Sneakers For Men',
 'sneaker men red 1258 - 6 Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Stylish Comfortable Lightweight, Breathable Walking Sho...',
 'Sneakers For Men',
 'Sneakers For Men']

In [20]:
Flipkart=pd.DataFrame()
Flipkart['Products']=titles
Flipkart['Price']=price_names
Flipkart

               Products Price
0            HIGHLANDER  ₹995
1            HIGHLANDER  ₹719
2             DUNKASTON  ₹343
3                BRUTON  ₹259
4   World Wear Footwear  ₹199
5                Chevit  ₹649
6              KWIK FIT  ₹399
7              RapidBox  ₹640
8                BRUTON  ₹299
9   World Wear Footwear  ₹199
10               corsac  ₹449
11                BIRDE  ₹399
12               BRUTON  ₹471
13           D-SNEAKERZ  ₹299
14             Magnolia  ₹448
15           HIGHLANDER  ₹719
16               BRUTON  ₹299
17           Shoes Bank  ₹298
18             URBANBOX  ₹198
19           HIGHLANDER  ₹719
20               Labbin  ₹499
21             Magnolia  ₹448
22               Kraasa  ₹444
23           HIGHLANDER  ₹796
24                   TR  ₹360
25             RapidBox  ₹680
26               Rzisbo  ₹494
27                Echor  ₹499
28         Stefano Rads  ₹240
29             ASTEROID  ₹474
30                CLYMB  ₹616
31             RapidBox  ₹630
32              Airland  ₹198
33            SCATCHITE  ₹398
34       luxury fashion  ₹489
35                BIRDE  ₹399
36                Zsyto  ₹311
37                 aadi  ₹339
38               Chevit  ₹259
39           HIGHLANDER  ₹995