In [3]:
#lets import all required librabries
import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
#lets first connect to web driver
driver=webdriver.Chrome(r'C:/Users/jishn/Downloads/chromedriver_win32/chromedriver.exe')   
driver=webdriver.Chrome('chromedriver.exe')
url='http://www.flipkart.com/'
driver.get(url)
search_product=driver.find_element_by_class_name("_3704LK")
search_product

In [6]:
#write on search bar
search_product.send_keys("Sunglasses")

In [7]:
#clicking using absolute xpath function
search_btn=driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
search_btn.click()

In [8]:
#lets extract all web elements having job titles
title_tags=driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
titles=[]

for i in title_tags:
    titles.append(i.text)

In [9]:
titles

['VINCENT CHASE',
 'povty',
 'SRPM',
 'SUNBEE',
 'ROZZETTA CRAFT',
 'Elligator',
 'PIRASO',
 'ROZZETTA CRAFT',
 'DEIXELS',
 'New Specs',
 'Fastrack',
 'VINCENT CHASE',
 'PIRASO',
 'PIRASO',
 'SHAAH COLLECTIONS',
 'ROYAL SON',
 'GANSTA',
 'Lee Topper',
 'Lee Topper',
 'ROYAL SON',
 'PHENOMENAL',
 'PIRASO',
 'kingsunglasses',
 'VINCENT CHASE',
 'PIRASO',
 'ROYAL SON',
 'Silver Kartz',
 'AISLIN',
 'SUNBEE',
 'kingsunglasses',
 'Elligator',
 'ROYAL SON',
 'kingsunglasses',
 'kingsunglasses',
 'Fastrack',
 'Arnette',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'ROZZETTA CRAFT']

In [12]:
    
price_tags=driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
price_names=[]

for i in price_tags:
    price_names.append(i.text)
price_names[0:40]

['₹980',
 '₹299',
 '₹198',
 '₹253',
 '₹474',
 '₹258',
 '₹229',
 '₹307',
 '₹202',
 '₹232',
 '₹679',
 '₹799',
 '₹225',
 '₹225',
 '₹165',
 '₹699',
 '₹198',
 '₹275',
 '₹199',
 '₹664',
 '₹289',
 '₹225',
 '₹239',
 '₹799',
 '₹375',
 '₹379',
 '₹246',
 '₹459',
 '₹284',
 '₹186',
 '₹189',
 '₹699',
 '₹184',
 '₹289',
 '₹639',
 '₹4,199',
 '₹327',
 '₹284',
 '₹379',
 '₹474']

In [13]:
Flipkart=pd.DataFrame()
Flipkart['Products']=titles
Flipkart['Price']=price_names
Flipkart

             Products   Price
0       VINCENT CHASE    ₹980
1               povty    ₹299
2                SRPM    ₹198
3              SUNBEE    ₹253
4      ROZZETTA CRAFT    ₹474
5           Elligator    ₹258
6              PIRASO    ₹229
7      ROZZETTA CRAFT    ₹307
8             DEIXELS    ₹202
9           New Specs    ₹232
10           Fastrack    ₹679
11      VINCENT CHASE    ₹799
12             PIRASO    ₹225
13             PIRASO    ₹225
14  SHAAH COLLECTIONS    ₹165
15          ROYAL SON    ₹699
16             GANSTA    ₹198
17         Lee Topper    ₹275
18         Lee Topper    ₹199
19          ROYAL SON    ₹664
20         PHENOMENAL    ₹289
21             PIRASO    ₹225
22     kingsunglasses    ₹239
23      VINCENT CHASE    ₹799
24             PIRASO    ₹375
25          ROYAL SON    ₹379
26       Silver Kartz    ₹246
27             AISLIN    ₹459
28             SUNBEE    ₹284
29     kingsunglasses    ₹186
30          Elligator    ₹189
31          ROYAL SON    ₹699
32     kingsunglasses    ₹184
33     kingsunglasses    ₹289
34           Fastrack    ₹639
35            Arnette  ₹4,199
36              NuVew    ₹327
37             GANSTA    ₹284
38          ROYAL SON    ₹379
39     ROZZETTA CRAFT    ₹474